eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8087
spring:
  application:
    name: API-GATEWAY
  #profiles:
  #default: dev
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowed-headers: "*"
            allowed-methods: "GET,POST,PUT,DELETE"
            allowed-origins: "http://localhost:4200"
      routes:
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/customers/**,/api/v1/customerGroup/**
          filters:
            - AuthenticationFilter

        - id: session-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/session/**,/api/v1/tag/**,/api/v1/remarks/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/users/**
  main:
    web-application-type: reactive
