package com.maveric.csp.entities;

public enum PreferredInvestmentProduct {
	
	MUTUAL_FUNDS,
	EQUITY_STOCKS,
	SIP,
	FIXED_DEPOSIT,
	GOVERNMENT_SECURITIES_LONG_TERM,
	GOVERNMENT_SECURITIES_T_BILLS,
	SOVEREIGN_GOLD_BOND,
	CORPORATE_BOND,
	UNIT_LINKED_INSURANCE_PLAN

}
